# Generated by Django 2.2.5 on 2019-09-23 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RDY', 'Ready for evaluation'), ('ICP', 'Information incomplete'), ('CCL', 'Cancelled'), ('TIQ', 'Task waiting in queue'), ('WIP', 'Evaluation in progress'), ('FIN', 'Evaluation finished'), ('ERR', 'Error occurred'), ('UNA', 'Unavailable')], max_length=20)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('RL', 'Repository Link Upload'), ('FU', 'File Upload')], max_length=20)),
                ('repo', models.URLField()),
                ('attachments', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refni_backend.Submission')),
            ],
        ),
    ]
