# Generated by Django 2.2.5 on 2019-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('RDY', 'Ready for evaluation'), ('WIP', 'Evaluation in progress'), ('FIN', 'Evaluation finished'), ('ERR', 'Evaluation error'), ('UNA', 'Unavailable')], max_length=20)),
                ('description', models.TextField()),
                ('report', models.TextField()),
                ('git_repo', models.URLField()),
                ('attachments', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
