# Generated by Django 2.2.6 on 2019-10-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refni_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='attachments',
            new_name='attachment',
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EvalReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Report', max_length=200)),
                ('content', models.TextField()),
                ('eval_start_time', models.DateTimeField()),
                ('eval_end_time', models.DateTimeField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refni_backend.Submission')),
            ],
        ),
    ]
